<div class="signup-login col-md-4 col-md-offset-4 col-sm-12">
  <h1>ユーザー新規登録</h1>
  <% if @user.errors.any? %>
    <div class="error_explanation user-errors">
      <h2><%= pluralize(@user.errors.count, "件") %> のエラーがあります。</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <ul>
  <%= form_with(model: @user, local: true) do |f| %>
    <li><%= f.text_field :name, placeholder: t('view.user_login_name') %></li>
    <li><%= f.text_field :email, placeholder: t('view.user_login_email') %></li>
    <li><%= f.text_field :password, placeholder: t('view.user_login_password') %></li>
    <li><%= f.text_field :password_confirmation, placeholder: t('view.user_login_password_confirmation') %></li>
    <li class="submit"><%= f.submit t('view.user_login_create') %></li>
  <% end %>
  </ul>
</div>